### Create One Event
POST http://localhost:3000/events
content-type: application/json

{
  "name": "first event",
  "description": "fun",
  "when": "12/12/2012",
  "address": "jurong"
}

### Find One Event
GET http://localhost:3000/events/2

### Find All Events
GET http://localhost:3000/events

### Update Event
PATCH http://localhost:3000/events/1
content-type: application/json

{
  "name": "updated first event",
  "description": "fun",
  "when": "12/12/2012",
  "address": "jurong"
}

### Delete Event
DELETE http://localhost:3000/events/1


### Practice

GET http://localhost:3000/events/practice

### Practice 2

GET http://localhost:3000/events/practice2


### Practice 3

GET http://localhost:3000/events/practice3


### Practice 4

GET http://localhost:3000/events/practice4

### Practice 5

GET http://localhost:3000/events/practice5


### School Create

POST http://localhost:3000/school/create

### Get Query Builder Event
GET http://localhost:3000/events/QueryBuilder